-- Create a table for document ratings
create table if not exists document_ratings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  pdf_name text not null,
  rating integer check (rating >= 1 and rating <= 5),
  is_approved boolean default false,
  comment text,
  extracted_data jsonb,

  constraint rating_range check (rating >= 1 and rating <= 5)
);

-- Enable Row Level Security (RLS) if you want to restrict access,
-- but for now we might keep it open or just allow anon inserts if that's the use case.
alter table document_ratings enable row level security;

-- Allow anonymous inserts (adjust based on your actual auth policy)
create policy "Enable insert for all users" on document_ratings for insert with check (true);
create policy "Enable read for all users" on document_ratings for select using (true);
